;;
;; utilities.lisp
;;
;; doloop (???)
list-array
list-row
map-alist
;;
;; algebra-support.lisp
;;
get-algebra-name
get-algebra-documentation
get-algebra-type
get-algebra-element-type
get-algebra-rels
get-algebra-rel-coding
get-algebra-inv-rels
get-algebra-equal-p
get-algebra-less-than-p
get-algebra-num-rels
get-algebra-zero
get-algebra-equalities
get-algebra-encoder
get-algebra-decoder
get-algebra-mult-table
get-algebra-multiplier
get-algebra-adder
get-algebra-inverter
print-algebra
find-algebra
delete-algebra
register-algebra
get-equality-element
make-type-of-algebra
make-coded-rels
make-zero-element
make-rel-assoc-list
make-less-than-p
make-encoder-function
make-decoder-function
encode-array-list
decode-array-list
make-multiplier-function
make-adder-function
inv-mapping
make-inverter-function
define-custom-algebra
define-discrete-algebra
define-algebra
dump-algebra
dump-mult-table
mult
relsys-to-conalg
;;
;; network-support.lisp
;;
get-network-algebra
get-network-arr
nref
element-of
determine-network-type
determine-network-size
print-network
create-network
read-network
copy-network
equal-nets-p
skew-of-p
inverse-net-of-p
consistentp
expand-network
;;
;; propagator.lisp
;;
square-array
equal-arrays-p
propagate-aux
propagate
;;
;; output-utilities.lisp
;;
dump-mult-table
show-table
write-terms
write-terms
write-prolog-list
write-table
find-abbrev
put-abbrev
make-abbrev
make-inv-abbrev
decode-abbrevs
write-table-2
setup-reused-abbrevs
table-info
print-out-table
print-out-table
write-algebra-table
sort-elem-defs
write-elem-defs
write-element-nets
find-mult-asymmetries
;;
;; tcn.lisp
;;
create-constraint-matrix
get-constraint-matrix
get-constrained-objects
get-alg-name
get-obj-eq-test
get-obj-id-key
create-constraint-network
create-constraint-network
get-constraint-relation
get-constraint-object
get-constraint-object1
get-constraint-object2
register-constrained-object-inputs-ok
register-constrained-object
register-constrained-objects
assert-relation
assert-constraint
assert-constraints
propagate-constraints
get-constraint
