b   before               <= <  < <  < <=
bi  after                <= >  > >  > <=
d   during               <= > < > < <
di  contains             < <  < >  > <=
e   equals               < = < > = <
f   finishes             < > < > = <
fi  finished-by          < < < > = <
m   meets                < < < = < <
mi  met-by               < > = > > <
o   overlaps             < < < > < <
oi  overlapped-by        < > < > > <
s   starts               < = < > < <
si  started-by           < = < > > <
pe  point-equals         = = = = = =
pf  point-finishes       = > = > = <
pfi point-finished-by    < < < = = =
ps  point-starts         = = < = < <
psi point-started-by     < = = > > =
rb  right-before         < <  < r~  r~ <=
rbi right-after          <= > r~ > r~ <
ro  right-overlaps       < < < > r~ <
roi right-overlapped-by  < > < > r~ <
rs  right-starts         < = < > r~ <
r~  right-incomparable   <= r~  r~ r~  r~ <=
l~  left-incomparable   <= l~  l~ l~  l~ <=
lbi left-after          < l~  l~ >  > <=
lb  left-before         <= l~ < l~ < <
lf  left-finishes       < l~ < > = <
loi left-overlapped-by  < l~ < > > <
lo  left-overlaps       < l~ < > < <
